services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - db_data_pandas:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  etl:
    build: .

    depends_on:
      - db

    volumes:
      - ./data:/data

volumes:
  db_data_pandas:
  arquivos_csv:
